
export const ALL_OBJECTS		= 0;
export const LAND				= 1;
export const BUILDING			= 2;
export const LETTER				= 3;
export const ROOMS_GROUP		= 4;
export const ROOM				= 5;
export const INDUSTRIAL_ZONE	= 6;
export const ASSET_GROUP		= 7;



export const ALLOWED_USAGE_SORT		= 0;
export const ADDRESS_SORT			= 1;
export const CADASTRAL_NUMBER_SORT	= 2;
export const NUMBER_OF_FLOORS_SORT	= 3;
export const FLOOR_SORT				= 4;
export const SPACE_SORT				= 5;
export const UNIT_COST_SORT			= 6;
export const COST_SORT				= 7;
export const DATE_SORT				= 8;

export const DEFAULT_MANTISSA		= 2;
export const NULL_MANTISSA			= 0;
export const DEFAULT_BOUNDARY		= 10;
export const NULL_BOUNDARY			= 0;
export const IS_WHOLE				= true;


export const PERMISSION_LIBRARY_FACTORS_MODULE					= "LIBRARY_FACTORS_MODULE";
export const PERMISSION_ADMIN_MODULE							= "ADMIN_MODULE";
export const PERMISSION_IMPORT_OFFERS_MODULE					= "IMPORT_OFFERS";
export const PERMISSION_FAST_SEARCH_MODULE						= "FAST_SEARCH_MODULE";
export const PERMISSION_ADVANCED_SEARCH_MODULE					= "ADVANCED_SEARCH_MODULE";
export const PERMISSION_DISTRIBUTION_ANALYSIS_MODULE			= "DISTRIBUTION_ANALYSIS_MODULE";
export const PERMISSION_CUSTOMIZE_DISTRIBUTION_ANALYSIS_MODULE	= "CUSTOMIZE_DISTRIBUTION_ANALYSIS_MODULE";
export const PERMISSION_ANALYTICS_MODULE						= "ANALYTICS_MODULE";
export const PERMISSION_GRAPHICAL_ANALYSIS_MODULE				= "GRAPHICAL_ANALYSIS_MODULE";
export const PERMISSION_ANALYSIS_OF_TRENDS_MODULE				= "ANALYSIS_OF_TRENDS_MODULE";
export const PERMISSION_RESULT_VIEW_MAP_MODULE					= "RESULT_VIEW_MAP_MODULE";
export const PERMISSION_RESULT_VIEW_TABLE_MODULE				= "RESULT_VIEW_TABLE_MODULE";
export const PERMISSION_RESULT_VIEW_ANALOGS_MODULE				= "RESULT_VIEW_ANALOGS_MODULE";
export const PERMISSION_SAVE_RESULT_MODULE						= "SAVE_RESULT_MODULE";
export const PERMISSION_SAVE_RESULT_TO_PDF_MODULE				= "SAVE_RESULT_TO_PDF_MODULE";
export const PERMISSION_COSTS_CALCULATING_MODULE				= "COSTS_CALCULATING_MODULE";
export const PERMISSION_ADD_OBJECT_OF_EVALUATION_MODULE			= "ADD_OBJECT_OF_EVALUATION_MODULE";
export const PERMISSION_SAVE_RESULT_TO_XLS_MODULE				= "SAVE_RESULT_TO_XLS_MODULE";